-- Schemas
CREATE SCHEMA "API";
CREATE SCHEMA "CMS";
CREATE SCHEMA "FLAGS";

-- Usuários
CREATE ROLE "API_USER" LOGIN PASSWORD 'API_PASSWORD';
CREATE ROLE "CMS_USER" LOGIN PASSWORD 'CMS_PASSWORD';
CREATE ROLE "FLAGS_USER" LOGIN PASSWORD 'FLAGS_PASSWORD';

-- Permissões API_USER
GRANT USAGE ON SCHEMA "API" TO "API_USER";
GRANT ALL ON ALL TABLES IN SCHEMA "API" TO "API_USER";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "API" TO "API_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "API" GRANT ALL ON TABLES TO "API_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "API" GRANT ALL ON SEQUENCES TO "API_USER";

-- Permissões CMS_USER (schema CMS + public para o Payload CMS)
GRANT ALL ON SCHEMA public TO "CMS_USER";
GRANT ALL ON ALL TABLES IN SCHEMA public TO "CMS_USER";
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "CMS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "CMS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "CMS_USER";
GRANT USAGE ON SCHEMA "CMS" TO "CMS_USER";
GRANT ALL ON ALL TABLES IN SCHEMA "CMS" TO "CMS_USER";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "CMS" TO "CMS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "CMS" GRANT ALL ON TABLES TO "CMS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "CMS" GRANT ALL ON SEQUENCES TO "CMS_USER";

-- Permissões FLAGS_USER
GRANT USAGE ON SCHEMA "FLAGS" TO "FLAGS_USER";
GRANT ALL ON ALL TABLES IN SCHEMA "FLAGS" TO "FLAGS_USER";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "FLAGS" TO "FLAGS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "FLAGS" GRANT ALL ON TABLES TO "FLAGS_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "FLAGS" GRANT ALL ON SEQUENCES TO "FLAGS_USER";

-- Create permission
GRANT CREATE ON SCHEMA "CMS" TO "CMS_USER";
GRANT CREATE ON SCHEMA "API" TO "API_USER";
GRANT CREATE ON SCHEMA "FLAGS" TO "FLAGS_USER";
