packages:
  - apps/backend/*
  - apps/frontend/*
  - packages/*

catalogs:
  ai:
    openai: ^4.85.1

  code-quality:
    prettier: ^3.3.3

  next16:
    next: ^16.0.1

  nextra4:
    nextra: ^4.6.0
    nextra-theme-docs: ^4.6.0
    pagefind: ^1.4.0

  rabbitmq:
    amqplib: 0.10.9
    amqp-connection-manager: ^4.1.14
    "@types/amqplib": 0.10.7

  react19:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0

  tooling:
    chalk: "4"
    dotenv: ^16.4.7
    readline: ^1.3.0
    turbo: ^2.1.2
    typescript: 5.9.2
    "@types/node": 24.5.2
    viem: ^2.23.2
