packages:
  - apps/backend/*
  - apps/frontend/*
  - apps/frontend/storybook/*
  - apps/e2e
  - packages/*
  - templates/*

catalogs:
  ai:
    openai: ^4.85.1

  api:
    graphql: ^16.8.1

  astro:
    "@astrojs/check": ^0.9.5
    "@astrojs/mdx": 4.3.10
    "@astrojs/node": ^9.0.0
    "@astrojs/react": ^4.4.2
    "@astrojs/rss": ^4.0.13
    "@astrojs/sitemap": ^3.6.0
    "@digi4care/astro-google-tagmanager": ^1.6.0
    "@justinribeiro/lite-youtube": ^1.8.2
    astro: ^5.15.9
    astro-auto-import: ^0.4.5
    astro-font: ^1.1.0
    github-slugger: ^2.0.0
    marked: ^16.4.0

  automation:
    husky: ^9.1.7
    hygen: ^6.2.11
    lint-staged: ^16.2.6

  code-quality:
    "@eslint/js": ^9.39.1
    "@next/eslint-plugin-next": ^15.5.0
    "@typescript-eslint/eslint-plugin": ^8.46.3
    "@typescript-eslint/parser": ^8.46.3
    eslint: ^9.39.1
    eslint-config-next: 15.4.7
    eslint-config-prettier: ^10.1.1
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-prettier: ^5.2.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.6.0
    globals: ^16.5.0
    junit: ^1.4.9
    prettier: ^3.3.3
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-tailwindcss: ^0.6.14
    sonarqube-scanner: ^4.3.2
    source-map-support: ^0.5.21
    typescript-eslint: ^8.46.3

  core-libs:
    "@hookform/resolvers": ^5.2.1
    class-validator: ^0.14.2
    react-hook-form: ^7.62.0
    zod: ^3.23.8

  docs:
    typedoc: ^0.28.14
    typedoc-plugin-markdown: ^4.9.0

  express:
    "@types/express": ^5.0.0

  logging:
    nestjs-pino: ^4.4.1
    pino: ^10.1.0
    pino-pretty: ^13.1.2

  nestjs11:
    "@nestjs/cli": ^11.0.0
    "@nestjs/common": ^11.0.1
    "@nestjs/config": ^4.0.2
    "@nestjs/core": ^11.0.1
    "@nestjs/platform-express": ^11.0.1
    "@nestjs/schematics": ^11.0.0
    "@nestjs/swagger": ^11.2.0
    "@nestjs/testing": ^11.0.1
    "@nestjs/microservices": ^11.1.6
    reflect-metadata: ^0.2.2
    nestjs-trpc: ^2.8.1
    rxjs: ^7.8.1

  next16:
    next: ^16.0.1

  nextra4:
    nextra: ^4.6.0
    nextra-theme-docs: ^4.6.0
    pagefind: ^1.4.0

  payload:
    "@payloadcms/db-postgres": 3.63.0
    "@payloadcms/next": 3.63.0
    "@payloadcms/richtext-lexical": 3.63.0
    "@payloadcms/translations": ^3.63.0
    "@payloadcms/ui": 3.63.0
    payload: 3.63.0

  prisma7:
    "@prisma/client": ^7.0.0
    prisma: ^7.0.0

  rabbitmq:
    "@types/amqplib": 0.10.7
    amqplib: 0.10.9
    amqp-connection-manager: ^4.1.14

  radix:
    "@radix-ui/react-accordion": ^1.2.12
    "@radix-ui/react-alert-dialog": ^1.1.15
    "@radix-ui/react-aspect-ratio": ^1.1.7
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-checkbox": ^1.3.3
    "@radix-ui/react-collapsible": 1.1.12
    "@radix-ui/react-context-menu": 2.2.16
    "@radix-ui/react-dialog": 1.1.15
    "@radix-ui/react-dropdown-menu": 2.1.16
    "@radix-ui/react-hover-card": 1.1.15
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-menubar": 1.1.16
    "@radix-ui/react-navigation-menu": 1.2.14
    "@radix-ui/react-popover": 1.1.15
    "@radix-ui/react-progress": ^1.1.7
    "@radix-ui/react-radio-group": ^1.3.8
    "@radix-ui/react-scroll-area": 1.2.10
    "@radix-ui/react-select": ^2.2.6
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-slider": ^1.3.6
    "@radix-ui/react-slot": ^1.0.2
    "@radix-ui/react-switch": ^1.2.6
    "@radix-ui/react-tabs": 1.1.13
    "@radix-ui/react-toggle": 1.1.10
    "@radix-ui/react-toggle-group": 1.1.11
    "@radix-ui/react-tooltip": ^1.2.8

  react19:
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    react: ^19.2.0
    react-dom: ^19.2.0

  search:
    fuse.js: ^7.1.0

  storybook9:
    "@storybook/addon-a11y": 9.1.8
    "@storybook/addon-docs": 9.1.8
    "@storybook/addon-links": 9.1.8
    "@storybook/addon-onboarding": 9.1.8
    "@storybook/react": 9.1.8
    "@storybook/react-vite": 9.1.8
    storybook: 9.1.8

  testing:
    "@playwright/test": 1.56.1
    "@testing-library/react": 16.3.0
    "@types/supertest": ^6.0.2
    "@vitest/coverage-v8": ^4.0.9
    playwright: 1.56.1
    playwright-core: 1.56.1
    supertest: 7.1.4
    vitest: 4.0.8

  tooling:
    "@swc/cli": ^0.7.8
    "@swc/core": ^1.13.5
    "@total-typescript/ts-reset": ^0.6.1
    "@types/node": 24.5.2
    chalk: "4"
    cross-env: ^7.0.3
    dotenv: ^17.2.3
    dotenv-cli: 11.0.0
    readline: ^1.3.0
    swc-loader: ^0.2.6
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    turbo: ^2.1.2
    typescript: 5.9.2
    unplugin-swc: 1.5.1
    viem: ^2.23.2
    vite: ^7.1.7

  trpc11:
    "@trpc/client": ^11.7.1
    "@trpc/server": ^11.7.1

  ui-libs:
    "@phosphor-icons/react": ^2.1.10
    "@remixicon/react": ^4.6.0
    "@tailwindcss/forms": ^0.5.10
    "@tailwindcss/typography": ^0.5.19
    "@tailwindcss/vite": ^4.1.14
    "@tailwindcss/postcss": ^4
    autoprefixer: ^10.4.21
    class-variance-authority: ^0.7.0
    clsx: ^2.1.1
    cmdk: ^1.1.1
    date-fns: ^4.1.0
    embla-carousel-react: ^8.6.0
    framer-motion: ^12.23.12
    input-otp: ^1.4.2
    jsdom: 26.1.0
    lucide-react: ^0.447.0
    next-themes: ^0.4.6
    postcss: ^8.4.47
    postcss-load-config: ^6
    react-day-picker: ^9.8.1
    react-icons: ^5.5.0
    react-medium-image-zoom: ^5.4.0
    react-resizable-panels: ^3.0.4
    recharts: 2.15.4
    remark-collapse: ^0.1.2
    remark-toc: ^9.0.0
    sonner: ^2.0.7
    sharp: 0.34.4
    tailwind-merge: ^2.3.0
    tailwindcss: ^4.1.18
    tailwindcss-animate: ^1.0.7
    vaul: ^1.1.2

  vite7:
    "@vitejs/plugin-react": ^5.0.3
    vite: ^7.1.9
    vite-tsconfig-paths: 5.1.4
