packages:
  - apps/backend/*
  - apps/frontend/*
  - packages/*

catalogs:
  ai:
    openai: ^4.85.1

  code-quality:
    prettier: ^3.3.3

  core-libs:
    "@hookform/resolvers": ^5.2.1
    "react-hook-form": ^7.62.0
    "zod": "^3.23.8"

  docs:
    typedoc: ^0.28.14
    "typedoc-plugin-markdown": ^4.9.0

  next16:
    next: ^16.0.1

  nextra4:
    nextra: ^4.6.0
    nextra-theme-docs: ^4.6.0
    pagefind: ^1.4.0

  rabbitmq:
    amqplib: 0.10.9
    amqp-connection-manager: ^4.1.14
    "@types/amqplib": 0.10.7

  radix:
    "@radix-ui/react-accordion": "^1.2.12"
    "@radix-ui/react-alert-dialog": "^1.1.15"
    "@radix-ui/react-aspect-ratio": ^1.1.7
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-checkbox": ^1.3.3
    "@radix-ui/react-collapsible": 1.1.12
    "@radix-ui/react-context-menu": 2.2.16
    "@radix-ui/react-dialog": 1.1.15
    "@radix-ui/react-dropdown-menu": 2.1.16
    "@radix-ui/react-hover-card": 1.1.15
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-menubar": 1.1.16
    "@radix-ui/react-navigation-menu": 1.2.14
    "@radix-ui/react-popover": 1.1.15
    "@radix-ui/react-progress": ^1.1.7
    "@radix-ui/react-radio-group": ^1.3.8
    "@radix-ui/react-scroll-area": 1.2.10
    "@radix-ui/react-select": ^2.2.6
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-slider": ^1.3.6
    "@radix-ui/react-slot": ^1.0.2
    "@radix-ui/react-switch": ^1.2.6
    "@radix-ui/react-tabs": 1.1.13
    "@radix-ui/react-toggle": 1.1.10
    "@radix-ui/react-toggle-group": 1.1.11
    "@radix-ui/react-tooltip": ^1.2.8

  react19:
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    react: ^19.2.0
    react-dom: ^19.2.0

  storybook9:
    "@storybook/addon-a11y": 9.1.8
    "@storybook/addon-docs": 9.1.8
    "@storybook/addon-links": 9.1.8
    "@storybook/addon-onboarding": 9.1.8
    "@storybook/react": 9.1.8
    "@storybook/react-vite": 9.1.8
    "storybook": 9.1.8

  styling:
    react-medium-image-zoom: ^5.4.0

  tooling:
    "@types/node": 24.5.2
    chalk: "4"
    dotenv: ^16.4.7
    readline: ^1.3.0
    turbo: ^2.1.2
    typescript: 5.9.2
    viem: ^2.23.2

  "ui-libs":
    autoprefixer: ^10.4.21
    "@phosphor-icons/react": ^2.1.10
    "@remixicon/react": ^4.6.0
    "class-variance-authority": ^0.7.0
    clsx: ^2.1.1
    cmdk: ^1.1.1
    "date-fns": ^4.1.0
    "embla-carousel-react": ^8.6.0
    "framer-motion": ^12.23.12
    "input-otp": ^1.4.2
    "lucide-react": ^0.447.0
    postcss: ^8.4.47
    "postcss-load-config": ^6
    "react-day-picker": ^9.8.1
    "react-resizable-panels": ^3.0.4
    recharts: 2.15.4
    sonner: ^2.0.7
    "tailwind-merge": ^2.3.0
    tailwindcss: ^3.4.13
    "tailwindcss-animate": ^1.0.7
    vaul: ^1.1.2
