name: "🐛 Bug Report"
description: "Report incorrect behavior, a crash, or a defect."
title: "[Bug] A short, clear description of the bug"
labels: ["type: bug", "priority: p1-high"]
body:
  - type: markdown
    attributes:
      value: "We're sorry this is happening! Please provide clear steps to reproduce the issue."
      
  - type: dropdown
    id: bounded-context
    attributes:
      label: "Relevant Bounded Context (Microservice)"
      description: "Where in the system did you find this bug?"
      options:
        - "bc: identity (User profiles, roles)"
        - "bc: auth (Login, passwords, JWTs)"
        - "bc: roadmap (The core domain: Roadmaps, Steps)"
        - "bc: interaction (Favorites, comments, progress)"
        - "bc: platform (DevOps, CI/CD, K8s, IaC)"
        - "bc: unknown (I'm not sure)"
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Clear, numbered steps to reproduce the bug."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error: '...'
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear description of what you expected to happen."
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "A clear description of what actually happened (include screenshots if possible)."
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: "Environment (Optional)"
      description: "What environment are you on? (e.g., Browser, OS, App Version)"