name: "🐛 Bug Report"
description: "Report incorrect behavior, a crash, or a defect."
title: "[Bug] "
labels: ["type: bug", "priority: p1-high"]
body:
  - type: dropdown
    id: bounded-context
    attributes:
      label: "Bounded Context"
      options:
        - "bc: identity"
        - "bc: auth"
        - "bc: roadmap"
        - "bc: interaction"
        - "bc: platform"
        - "bc: unknown"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error: '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected vs Actual"
      description: "What should happen vs what actually happens."
    validations:
      required: true
