name: "✨ Feature Request (User Story)"
description: "Suggest a new feature or enhancement using our BDD format."
title: "[Feature] As a [Persona], I want [Action], so that [Value]"
labels: ["type: feature", "priority: p2-medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please provide the details below.
        
  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Clearly state the user story. Who is the persona? What do they want? Why do they want it?"
      placeholder: |
        As a [Persona, e.g., Learner],
        I want [Action, e.g., to favorite a Roadmap],
        So that [Value, e.g., I can easily find it later].
    validations:
      required: true
      
  - type: textarea
    id: bdd-scenarios
    attributes:
      label: "Acceptance Criteria (BDD / Gherkin)"
      description: "This is crucial. Describe the behavior of the feature using BDD scenarios. This will become our living documentation."
      placeholder: |
        Feature: [Title of the Feature, e.g., Roadmap Favoriting]
        
          Scenario: Learner favorites a Roadmap
            Given I am a logged-in "Learner"
            And I am viewing a "Roadmap" that I have not favorited
            When I click the "Favorite" button
            Then my action should be saved
            And the "Favorite" button should appear as "Favorited"
            
          Scenario: Learner unfavorites a Roadmap
            Given I am a logged-in "Learner"
            And I am viewing a "Roadmap" that I have already favorited
            When I click the "Favorited" button
            Then my action should be saved
            And the "Favorite" button should appear as "Favorite"
      render: gherkin
    validations:
      required: true
      
  - type: dropdown
    id: bounded-context
    attributes:
      label: "Relevant Bounded Context (Microservice)"
      description: "Which part of the system does this feature belong to? (Helps us with our DDD/Monorepo labels)"
      options:
        - "bc: identity (User profiles, roles)"
        - "bc: auth (Login, passwords, JWTs)"
        - "bc: roadmap (The core domain: Roadmaps, Steps)"
        - "bc: interaction (Favorites, comments, progress)"
        - "bc: platform (DevOps, CI/CD, K8s, IaC)"
        - "bc: unknown (I'm not sure)"
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context or Mockups"
      description: "Add any other context, notes, or screenshots about the feature request here."