name: "🛠️ Technical Task"
description: "Refactoring, CI/CD, docs, tech debt, or internal improvements."
title: "[Task] "
labels: ["type: chore"]
body:
  - type: dropdown
    id: bounded-context
    attributes:
      label: "Bounded Context"
      options:
        - "bc: identity"
        - "bc: auth"
        - "bc: roadmap"
        - "bc: interaction"
        - "bc: platform"
        - "bc: unknown"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "What needs to be done and why?"
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: "Definition of Done"
      placeholder: |
        - [ ] ...
        - [ ] ...
