name: "🛠️ Technical Task (Chore, Docs, Tech Debt)"
description: "For internal improvements: refactoring, CI/CD, documentation, etc."
title: "[Task] A short title for the technical task"
labels: ["type: chore"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: "Type of Task"
      description: "What kind of technical task is this?"
      options:
        - "type: chore (e.g., update dependencies, internal script)"
        - "type: docs (e.g., update README, write ADR)"
        - "type: tech-debt (e.g., refactor legacy code, improve query)"
    validations:
      required: true

  - type: dropdown
    id: bounded-context
    attributes:
      label: "Relevant Bounded Context (Microservice)"
      description: "Which part of the system does this task affect?"
      options:
        - "bc: identity"
        - "bc: auth"
        - "bc: roadmap"
        - "bc: interaction"
        - "bc: platform"
        - "bc: unknown"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: "Task Description"
      description: "What needs to be done and why?"
    validations:
      required: true
      
  - type: textarea
    id: definition-of-done
    attributes:
      label: "Definition of Done (DoD)"
      description: "A checklist of what 'done' looks like for this task."
      placeholder: |
        - [ ] Code is refactored
        - [ ] Unit tests are passing
        - [ ] Documentation is updated