/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { createUserDto } from "./modules/user/application";

const appRouter = t.router({
  auth: t.router({
    register: publicProcedure
      .input(createUserDto)
      .output(z.object({ message: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
  }),
});

export type AppRouter = typeof appRouter;
