---
to: apps/frontend/<%=name%>/src/app/layout.tsx
---
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "@repo/ui-web/globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "<%=name%>",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
