#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Exit immediately if a command exits with a non-zero status
set -e

# Run lint-staged
echo "⏳ Running lint-staged on staged files..."
pnpx lint-staged

echo "✅ All checks passed. Committing."