#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "🧪 Running unit tests before push..."
echo "⏳ Running tests..."
pnpm test:unit:coverage

echo "🧱 Building packages before push..."
echo "⏳ Building packages..."
pnpm build

echo "🎉 All checks passed! Pushing."