#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "🧪 Running unit tests on changed packages (vs. origin/main) before push..."
echo "⏳ Running tests..."
pnpm turbo run test:unit --since=origin/main

echo "🧱 Building changed packages (vs. origin/main) before push..."
echo "⏳ Building packages..."
pnpm turbo run build --since=origin/main

echo "🎉 All checks passed! Pushing."